version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: traveldb
      MYSQL_USER: user
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    image: your-spring-boot-image
    container_name: backend
    build:
      context: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/traveldb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
    driver: local
